"""BNBAgent sidecar — ERC-8004 identity registration after agent deploy.

Usage:
  python register_identity.py --agent-id <uuid> --endpoint <public-meta-url> [--trading-wallet 0x...]

Requires: bag CLI (bnbagent-studio) optionally. Falls back to writing a
studio.toml stub and recording the intended registration for later `bag erc8004 register`.
"""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from pathlib import Path


def write_studio_toml(agent_dir: Path, trading_wallet: str | None, endpoint: str) -> Path:
    agent_dir.mkdir(parents=True, exist_ok=True)
    toml_path = agent_dir / "studio.toml"
    wallet_line = f'address = "{trading_wallet}"' if trading_wallet else 'address = ""'
    content = f"""# Auto-generated by Neural Alpha deploy hook
[agent]
name = "neural-alpha-{agent_dir.name[:8]}"
endpoint = "{endpoint}"

[wallet]
kind = "evm-local"
{wallet_line}

[network]
chain = "bsc"
"""
    toml_path.write_text(content, encoding="utf-8")
    return toml_path


def try_bag_register(endpoint: str, agent_dir: Path) -> dict:
    """Attempt `bag erc8004 register` if bag CLI is available."""
    try:
        result = subprocess.run(
            ["bag", "erc8004", "register", "--endpoint", endpoint],
            cwd=str(agent_dir),
            capture_output=True,
            text=True,
            timeout=120,
        )
        return {
            "ok": result.returncode == 0,
            "stdout": result.stdout.strip(),
            "stderr": result.stderr.strip(),
            "method": "bag",
        }
    except FileNotFoundError:
        return {
            "ok": False,
            "error": "bag CLI not found — studio.toml written for later registration",
            "method": "stub",
        }
    except subprocess.TimeoutExpired:
        return {"ok": False, "error": "bag register timed out", "method": "bag"}


def main() -> int:
    parser = argparse.ArgumentParser(description="Register ERC-8004 identity for a Neural Alpha agent")
    parser.add_argument("--agent-id", required=True)
    parser.add_argument("--endpoint", required=True, help="Public /api/meta URL")
    parser.add_argument("--trading-wallet", default=None)
    parser.add_argument(
        "--data-dir",
        default=os.environ.get("AGENT_DATA_DIR", "./data/agents"),
    )
    args = parser.parse_args()

    agent_dir = Path(args.data_dir) / args.agent_id / "bnbagent"
    write_studio_toml(agent_dir, args.trading_wallet, args.endpoint)

    result = try_bag_register(args.endpoint, agent_dir)
    out = {
        "agentId": args.agent_id,
        "endpoint": args.endpoint,
        "studioToml": str(agent_dir / "studio.toml"),
        **result,
    }

    # Persist result for platform to pick up
    result_path = agent_dir / "erc8004-result.json"
    result_path.write_text(json.dumps(out, indent=2), encoding="utf-8")
    print(json.dumps(out))
    return 0 if result.get("ok") or result.get("method") == "stub" else 1


if __name__ == "__main__":
    sys.exit(main())
